DEBUG 2020-07-06 01:23:28.131 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-06 01:23:28.131 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-06 01:23:28.145 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-06 01:23:28.145 UTC: 	 Executing command: 'status'
DEBUG 2020-07-06 01:23:28.145 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-07-06 01:23:28.146 UTC: 	 Error: crab_full_run2_2018_WG1Jets_version1 is not a valid CRAB project directory.
ERROR 2020-07-06 01:23:28.146 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WG1Jets_version1 is not a valid CRAB project directory.
INFO 2020-07-06 01:23:28.149 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/fullRun2VBSWA/18/tight/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-07-06 01:23:28.434 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-06 01:23:28.434 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-06 01:23:28.447 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-06 01:23:28.447 UTC: 	 Executing command: 'status'
DEBUG 2020-07-06 01:23:28.447 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-07-06 01:23:28.448 UTC: 	 Error: crab_full_run2_2018_WG2Jets_version1 is not a valid CRAB project directory.
ERROR 2020-07-06 01:23:28.448 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WG2Jets_version1 is not a valid CRAB project directory.
INFO 2020-07-06 01:23:28.450 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/fullRun2VBSWA/18/tight/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-07-06 13:28:26.850 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-06 13:28:26.851 UTC: 	 Running on: Linux lxplus701.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-06 13:28:26.864 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-06 13:28:26.864 UTC: 	 Executing command: 'status'
DEBUG 2020-07-06 13:28:26.864 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-07-06 13:28:26.865 UTC: 	 Error: crab_full_run2_2018_WG1Jets_version1 is not a valid CRAB project directory.
ERROR 2020-07-06 13:28:26.865 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WG1Jets_version1 is not a valid CRAB project directory.
INFO 2020-07-06 13:28:26.869 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/fullRun2VBSWA/18/tight/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-07-06 13:28:27.220 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-06 13:28:27.221 UTC: 	 Running on: Linux lxplus701.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-06 13:28:27.237 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-06 13:28:27.237 UTC: 	 Executing command: 'status'
DEBUG 2020-07-06 13:28:27.237 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-07-06 13:28:27.238 UTC: 	 Error: crab_full_run2_2018_WG2Jets_version1 is not a valid CRAB project directory.
ERROR 2020-07-06 13:28:27.238 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WG2Jets_version1 is not a valid CRAB project directory.
INFO 2020-07-06 13:28:27.240 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/fullRun2VBSWA/18/tight/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 00:26:51.396 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 00:26:51.397 UTC: 	 Running on: Linux lxplus742.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 00:26:51.397 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 00:26:51.397 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 00:26:51.398 UTC: 	 Error: crab_full_run2_2018_DY_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 00:26:51.398 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_DY_version1 is not a valid CRAB project directory.
INFO 2020-11-14 00:26:51.415 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 00:28:06.105 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 00:28:06.105 UTC: 	 Running on: Linux lxplus742.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 00:28:06.106 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 00:28:06.106 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 00:28:06.107 UTC: 	 Error: crab_full_run2_2018_WGJJ_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 00:28:06.107 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WGJJ_version1 is not a valid CRAB project directory.
INFO 2020-11-14 00:28:06.109 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 00:28:06.435 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 00:28:06.435 UTC: 	 Running on: Linux lxplus742.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 00:28:06.435 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 00:28:06.436 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 00:28:06.437 UTC: 	 Error: crab_full_run2_2018_WGJets_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 00:28:06.437 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WGJets_version1 is not a valid CRAB project directory.
INFO 2020-11-14 00:28:06.439 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 13:58:43.588 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 13:58:43.588 UTC: 	 Running on: Linux lxplus7111.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 13:58:43.588 UTC: 	 Executing command: 'submit'
DEBUG 2020-11-14 13:58:43.589 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-11-14 13:58:43.590 UTC: 	 Will use CRAB configuration file CrabJobsSrc/mc/crab3_analysisDY.py
DEBUG 2020-11-14 13:58:43.590 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-11-14 13:58:43.594 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-11-14 13:58:43.595 UTC: 	 Task requests 5500 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-11-14 13:58:43.595 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Task requests 5500 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-11-14 13:58:43.598 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 14:31:37.658 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 14:31:37.659 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 14:31:37.659 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 14:31:37.659 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 14:31:37.660 UTC: 	 Error: crab_full_run2_2018_DY_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 14:31:37.660 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_DY_version1 is not a valid CRAB project directory.
INFO 2020-11-14 14:31:37.665 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 14:33:00.694 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 14:33:00.694 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 14:33:00.694 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 14:33:00.694 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 14:33:00.695 UTC: 	 Error: crab_full_run2_2018_WGJJ_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 14:33:00.696 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WGJJ_version1 is not a valid CRAB project directory.
INFO 2020-11-14 14:33:00.697 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-14 14:33:01.057 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-14 14:33:01.058 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-14 14:33:01.058 UTC: 	 Executing command: 'resubmit'
DEBUG 2020-11-14 14:33:01.058 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2020-11-14 14:33:01.059 UTC: 	 Error: crab_full_run2_2018_WGJets_version1 is not a valid CRAB project directory.
ERROR 2020-11-14 14:33:01.059 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_full_run2_2018_WGJets_version1 is not a valid CRAB project directory.
INFO 2020-11-14 14:33:01.061 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-11-15 06:43:53.583 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-11-15 06:43:53.584 UTC: 	 Running on: Linux lxplus733.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-11-15 06:43:53.584 UTC: 	 Executing command: 'submit'
DEBUG 2020-11-15 06:43:53.584 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-11-15 06:43:53.585 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/mc/crab3_analysisDY.py
DEBUG 2020-11-15 06:43:53.585 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-11-15 06:43:53.587 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-11-15 06:43:53.587 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_DY_version5' already exists 
Please change the requestName in the config file
ERROR 2020-11-15 06:43:53.587 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_DY_version5' already exists 
Please change the requestName in the config file
INFO 2020-11-15 06:43:53.645 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG/18/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-03-01 15:49:19.593 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-03-01 15:49:19.594 UTC: 	 Running on: Linux lxplus730.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-01 15:49:19.594 UTC: 	 Executing command: 'kill'
DEBUG 2021-03-01 15:49:19.594 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2021-03-01 15:49:19.595 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_s_version1
ERROR 2021-03-01 15:49:19.595 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_s_version1
INFO 2021-03-01 15:49:19.612 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-03-01 15:49:31.696 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-03-01 15:49:31.697 UTC: 	 Running on: Linux lxplus730.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-01 15:49:31.697 UTC: 	 Executing command: 'kill'
DEBUG 2021-03-01 15:49:31.697 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2021-03-01 15:49:31.698 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_tbar_version1
ERROR 2021-03-01 15:49:31.699 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_tbar_version1
INFO 2021-03-01 15:49:31.705 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-03-01 15:51:01.181 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-03-01 15:51:01.182 UTC: 	 Running on: Linux lxplus730.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-03-01 15:51:01.182 UTC: 	 Executing command: 'kill'
DEBUG 2021-03-01 15:51:01.182 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2021-03-01 15:51:01.183 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_s_version1
ERROR 2021-03-01 15:51:01.184 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_ST_s_version1
INFO 2021-03-01 15:51:01.185 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-04-21 14:29:29.342 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 14:29:29.343 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 14:29:29.343 UTC: 	 Executing command: 'submit'
DEBUG 2021-04-21 14:29:29.345 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2021-04-21 14:29:29.369 UTC: 	 Will use CRAB configuration file CrabJobsSrc/mc/crab3_analysisWW.py
DEBUG 2021-04-21 14:29:29.370 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-04-21 14:29:29.405 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-04-21 14:29:29.408 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WW_version2' already exists 
Please change the requestName in the config file
ERROR 2021-04-21 14:29:29.408 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WW_version2' already exists 
Please change the requestName in the config file
INFO 2021-04-21 14:29:29.482 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-04-21 14:31:29.596 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 14:31:29.597 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 14:31:29.597 UTC: 	 Executing command: 'kill'
DEBUG 2021-04-21 14:31:29.597 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
ERROR 2021-04-21 14:31:29.608 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WW_version2
ERROR 2021-04-21 14:31:29.609 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 643, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 505, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WW_version2
INFO 2021-04-21 14:31:29.621 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-04-22 00:16:04.148 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-22 00:16:04.148 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-22 00:16:04.149 UTC: 	 Executing command: 'submit'
DEBUG 2021-04-22 00:16:04.149 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2021-04-22 00:16:04.150 UTC: 	 Will use CRAB configuration file CrabJobsSrc/mc/crab3_analysisWZ.py
DEBUG 2021-04-22 00:16:04.150 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-04-22 00:16:04.175 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-04-22 00:16:04.175 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WZ_version2' already exists 
Please change the requestName in the config file
ERROR 2021-04-22 00:16:04.176 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_WZ_version2' already exists 
Please change the requestName in the config file
INFO 2021-04-22 00:16:04.214 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-05-31 17:27:40.589 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-05-31 17:27:40.590 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-05-31 17:27:40.590 UTC: 	 Executing command: 'submit'
DEBUG 2021-05-31 17:27:40.590 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2021-05-31 17:27:40.591 UTC: 	 Will use CRAB configuration file CrabJobsSrc/mc/crab3_analysisW0Jets.py
DEBUG 2021-05-31 17:27:40.591 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-05-31 17:27:40.592 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-05-31 17:27:40.592 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_check_fakephoton2_W0Jets_version1' already exists 
Please change the requestName in the config file
ERROR 2021-05-31 17:27:40.592 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_check_fakephoton2_W0Jets_version1' already exists 
Please change the requestName in the config file
INFO 2021-05-31 17:27:40.627 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2021-06-02 14:44:28.543 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-02 14:44:28.543 UTC: 	 Running on: Linux lxplus705.cern.ch 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-02 14:44:28.543 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-02 14:44:28.544 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2021-06-02 14:44:28.545 UTC: 	 Will use CRAB configuration file CrabJobsSrc/mc/crab3_analysisW0Jets.py
DEBUG 2021-06-02 14:44:28.546 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-02 14:44:28.565 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-02 14:44:28.565 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_check_fakephoton2_W0Jets_version1' already exists 
Please change the requestName in the config file
ERROR 2021-06-02 14:44:28.565 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_full_run2_2018_PUJetID_check_fakephoton2_W0Jets_version1' already exists 
Please change the requestName in the config file
INFO 2021-06-02 14:44:28.590 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2022-05-12 08:23:06.461 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-05-12 08:23:06.461 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-05-12 08:23:06.461 UTC: 	 Executing command: 'submit'
DEBUG 2022-05-12 08:23:06.461 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2022-05-12 08:23:06.462 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/mc/crab3_analysisWGJJ_sherpa.py
DEBUG 2022-05-12 08:23:06.462 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-05-12 08:23:06.462 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-05-12 08:23:06.463 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_jec_source_v2_full_run2_2018_WGJJ_sherpa_v1' already exists 
Please change the requestName in the config file
ERROR 2022-05-12 08:23:06.463 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_jec_source_v2_full_run2_2018_WGJJ_sherpa_v1' already exists 
Please change the requestName in the config file
INFO 2022-05-12 08:23:06.573 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2022-05-12 09:04:29.528 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-05-12 09:04:29.528 UTC: 	 Running on: Linux lxplus724.cern.ch 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-05-12 09:04:29.528 UTC: 	 Executing command: 'submit'
DEBUG 2022-05-12 09:04:29.529 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2022-05-12 09:04:29.559 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/mc/crab3_analysisWGJJ_sherpa.py
DEBUG 2022-05-12 09:04:29.559 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-05-12 09:04:29.571 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-05-12 09:04:29.575 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_jec_source_v2_full_run2_2018_WGJJ_sherpa_v1' already exists 
Please change the requestName in the config file
ERROR 2022-05-12 09:04:29.575 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab_jec_source_v2_full_run2_2018_WGJJ_sherpa_v1' already exists 
Please change the requestName in the config file
INFO 2022-05-12 09:04:29.624 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/18/18_tight_for_analysis_PUJetID/CMSSW_10_2_21/src/VAJets/PKUTreeMaker/test/crab.log
